# Items that apply to adjective with eureka-server-clustered:
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/,http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

# Items that apply to adjective with standalone eureka-server:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

words: reasonable,leaky,suspicious,ordinary,unlikely
