# Items that apply to noun with eureka-server-clustered:
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

# Items that apply to noun with standalone eureka-server:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

words: boat,book,vote,seat,backpack,partition,groundhog